### ISSUE TITLE
Pseudocode Outline

### ISSUE THREAD

**Issue by mfcodingbc** [mfcodingbc/friendly-parakeet#1]
## Create Outline

- write pseudocode in script outlining steps for creating the necessary code and where to incorporate said code

**Comment by ketan-rathod-713** [comment]
- first make function passwordGenerator
-  And then make a string of different things like lowercase,Uppercases and Numbers and special char and all 
-  Let I want lowercase and special char in my password then randomly select both using math.random (after concating)
- Or let I want minimum two characters to be Uppercase then select 2 times from Uppercase string and other letters from other character strings 
- If i dont want special char. inside password then just concate other strings except it and then select randomly 

may this will help.
